name: tests

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, review_requested]
    branches:
      - master
        # paths:
        # - "**/*.java"

jobs:
  tests:

    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}

    steps:
    - uses: actions/checkout@v1
    - name: installing Java and Java libraries
      run: sudo apt-get install -y openjdk-13-jdk openjfx libopenjfx-java
    - name: installing JUnit 5
      run: |
        mkdir junit
        wget https://repo1.maven.org/maven2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar
        wget https://repo1.maven.org/maven2/org/apiguardian/apiguardian-api/1.1.1/apiguardian-api-1.1.1.jar
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.6.3/junit-platform-commons-1.6.3.jar
        wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-params/5.6.3/junit-jupiter-params-5.6.3.jar
        wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.6.3/junit-jupiter-api-5.6.3.jar
        wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter/5.6.3/junit-jupiter-5.6.3.jar
        mv *.jar junit
    - name: compiling
      run: |
        mkdir -p bin/jetuml
        find . -name "*.java" > files.txt 
        javac -cp src:test -p junit:/usr/share/openjfx/lib --add-reads jetuml=org.junit.jupiter.params --add-reads jetuml=org.junit.jupiter.api --add-modules org.junit.jupiter.params,org.junit.jupiter.api,javafx.controls,javafx.swing -d bin/jetuml @files.txt
        cd src
        cp --parents `find -name '*.css'` ../bin/jetuml
        cp --parents `find -name '*.properties'` ../bin/jetuml
        cd ../test
        cp --parents `find -name '*.properties'` ../bin/jetuml
        cd ..
    - name: running the tests
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.2/junit-platform-console-standalone-1.7.2.jar
        java -p /usr/share/openjfx/lib --add-modules javafx.controls,javafx.swing -jar junit-platform-console-standalone-1.7.2.jar --scan-classpath=bin/jetuml --include-package=jetuml
        # java -p junit:/usr/share/openjfx/lib:bin/jetuml --add-modules org.junit.jupiter.params,org.junit.jupiter.api,javafx.controls,javafx.swing,jetuml org.junit.runner.JUnitCore TestLine
